spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.12:3306/cpdemo
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


