spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  spring:
    thymeleaf:
      prefix:
        classpath: /templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
      cache: false


